function strings = GetText
% This function loads all the strings used for the introduction/instruction
% slides.
%
% The strings can be changed and adapted!
%
% Author: Janne Nold
% Last modified: 28.10.21

%% Weclome

strings.welcome = ['Herzlich Willkommen und vielen Dank für Ihre Teilnahme.\n\n\n\n ' ...
    'Bitte drücken Sie eine beliebige Taste,\n um fortzufahren.'];

strings.introduction1 = ['Wir werden heute zunächst verschiedene Druckintensitäten kalibrieren\n\n ' ...
    'Dafür erhalten Sie nun zunächst Druckreize am Oberarm.\n\n\n\n' ...
    'Bitte drücken Sie die rechte Taste,\n um fortzufahren.'];

strings.introduction2 = ['Anschließend kalibrieren wir die Intensitäten auf dem Fahrrad.\n\n ' ...
    'Bitte drücken Sie eine beliebige Taste,\n um fortzufahren.'];

strings.introduction2 = ['Wir beginnen zunächst mit der individuellen Kalibrierung des Druckschmerzes.\n\n\n\n' ...
    'Bitte drücken Sie die rechte Taste,\n um fortzufahren.'];

%% Pre exposure

strings.preExposure1 = ['Gleich erhalten Sie über die Druckmanschette/Thermode eine Reihe\n\n' ...
    'an Reizen, die leicht schmerzhaft sein können.\n\n\n\n' ...
    'Bitte drücken Sie die rechte Taste,\n um fortzufahren.'];

strings.preExposure2 = ['Sobald ein Reiz kommt, wird das Fixationskreuz\n\n' ...
    'auf dem Bildschirm rot.\n\n\n\n'...
    'Bitte drücken Sie die rechte Taste,\n um fortzufahren.'];

strings.preExposure3 = ['Bitte geben Sie anschließend an, ob ein Reiz SCHMERZHAFT\n\n' ...
    'oder NICHT SCHMERZHAFT war.\n\n\n\n' ...
    'Bitte drücken Sie die rechte Taste,\n um fortzufahren.'];

strings.preExposure4 = ['Falls Sie keine Fragen mehr haben,\n\n' ...
    ' werden wir gleich beginnen.\n\n\n\n'];


%% VAS training

strings.vastraining0 = ['Im Laufe der Studie müssen Sie Bewertungen der Schmerzhaftigkeit \n\n' ...
    'abgeben. \n\n\n\n' ...
    'Bitte drücken Sie die rechte Taste,\n um fortzufahren.'];

strings.vastraining01 = ['Im vorherigen Teil haben wir Ihre Schmerzschwelle für\n\n ' ...
    'den Druckreiz (bzw. Hitzereiz) bestimmt, also der Punkt,\n\nab dem Sie den Reiz als schmerzhaft empfinden.\n\n\n\n' ...
    'Bitte drücken Sie die rechte Taste,\n um fortzufahren.'];

strings.vastraining1 = ['Im Folgenden werden Sie mit der Antwortskala \n\n' ...
    'für den Reiz vertraut gemacht.\n\n\n\n' ...
    'Bitte drücken Sie die rechte Taste,\n um fortzufahren.'];


strings.vastraining2 = ['Bitte nutzen Sie die rechte und linke Pfeiltaste, \n\n' ...
    'um den Cursor zu bewegen. \n\n\n\n' ...
    'Bitte drücken Sie die rechte Taste,\n um fortzufahren.'];

strings.vastraining3 = ['Ihre letzte Cursorposition wird als Antwort eingeloggt.\n\n' ...
    'Sie haben 5 Sekunden Zeit für Ihre Antwort.\n\n\n\n' ...
    'Bitte drücken Sie die rechte Taste,\n um fortzufahren.'];

strings.vastraining4 = ['Sie werden nach jedem Reiz gefragt, \n\n' ...
    'wie SCHMERZHAFT der letzte Reiz war.\n\n\n\n' ...
    'Bitte drücken Sie die rechte Taste,\n um fortzufahren.'];

strings.vastraining5 = ['Sie werden nach jedem Druckreiz gefragt,\n\n' ...
    'wie UNANGENEHM der Druck war.\n\n\n\n' ...
    'Bitte drücken Sie die rechte Taste,\n um fortzufahren.'];

strings.vastraining6 = ['Bitte bewegen Sie IMMER mindestens einmal den Cursor,\n\n' ...
    ' auch wenn die Position auf der Skala bereits Ihrer Antwort entspricht.\n\n\n\n' ...
    'Bitte drücken Sie die rechte Taste,\n um fortzufahren.'];

strings.vastraining7 = ['Falls Sie keine Fragen mehr haben,\n\n' ...
    ' werden wir gleich beginnen.\n\n\n\n'];

strings.vastraining8 = ['SCHMERZHAFT'];

strings.vastraining9 = ['UNANGENEHM'];

strings.vastraining10 = ['DEUTLICH'];


%% Calibration 

strings.calibration1 = ['Nun wollen wir zunächst individuell\n\n ' ...
    'verschiedene Intensitäten kalibrieren.\n\n\n\n' ...
    'Bitte drücken Sie die rechte Taste,\n um fortzufahren.'];

strings.calibration2 = ['Bewerten Sie bitte nach jedem Reiz,\n\n ' ...
    'wie SCHMERZHAFT der Reiz war.\n\n\n\n' ...
    'Bitte drücken Sie die rechte Taste,\n um fortzufahren.'];
% 
% strings.calibration3 = ['"Minimaler Schmerz" = 0 und "unteräglicher Schmerz" = 100. ' ...
%    '\n\n\n\n' ...
%    'Bitte drücken Sie die rechte Taste,\n um fortzufahren.'];

strings.calibration4 = ['Falls Sie keine Fragen mehr haben,\n\n' ...
    ' werden wir gleich beginnen.\n\n\n\n'];

%% Experiment

strings.experiment1 = ['Wir starten nun mit dem Versuch.\n ' ...
    '\n\n\n\n' ...
    'Bitte dr�cken Sie die rechte Taste,\n um fortzufahren.'];

strings.experiment2 = ['Sie werden in 4 Blöcken von 10 Minuten fahrradfahren.\n\n ' ...
    'Anschlie�end bekommen Sie die kalibrierten Druck- und Hitzereize �ber die Manschette.\n\n\n\n' ...
    'Bitte dr�cken Sie die rechte Taste,\n um fortzufahren.'];

strings.experiment3 = ['Bewerten Sie bitte nach jedem Reiz,\n\n' ...
    'wie SCHMERZHAFT\n\n' ...
    'Sie den Reiz wahrgenommen haben.\n\n\n\n' ...
    'Bitte dr�cken Sie die rechte Taste,\n um fortzufahren.'];


strings.experiment7 = ['Sie k�nnen jetzt noch letzte Fragen stellen!\n '];

strings.experiment8 = ['Nutzen Sie die linke und rechte Taste zum bewegen des Cursors.\n' ...
    'Sie haben immer 5 Sekunden Zeit f�r Ihre Bewertung. \n\n\n\n' ...
    'Bitte dr�cken Sie eine beliebige Taste,\n um fortzufahren.'];

%% Goodbye

strings.goodbye1 = ['Der Druchgang ist nun beendet.\n\n' ...
    'Der Versuchsleiter wird sich gleich bei Ihnen melden.'];
%% Others

strings.exercise1= ['Gleich beginnt das Fahrradfahren!\n' ...
    'Bitte nehmen Sie die richtige Position ein\n und halten Sie sich bereit... \n'];

strings.pain1 = ['Nun werden Sie verschiedene Druck-Stimuli bekommen,\n' ...
    'die Sie bitte nach jedem Mal bewerten.\n'];

end